# -------------------------------------------------------------------------
# AUTHOR: Musa Waghu
# FILENAME: title of the source file
# SPECIFICATION: description of the program
# FOR: CS 4210- Assignment #4
# TIME SPENT: how long it took you to complete the assignment
# -----------------------------------------------------------*/

# IMPORTANT NOTE: DO NOT USE ANY ADVANCED PYTHON LIBRARY TO COMPLETE THIS CODE SUCH AS numpy OR pandas. You have to work here only with standard vectors and arrays

# importing some Python libraries
from sklearn import tree
from sklearn.utils import resample
from sklearn.ensemble import RandomForestClassifier
import csv
import numpy as np
classVotes = []  # this array will be used to count the votes of each classifier

# reading the training data from a csv file and populate dbTraining
with open('optdigits.tra', newline='') as csvDataFile:
    # open file as csv file
    csvReader = csv.reader(csvDataFile)

    # loop over rows
    for row in csvReader:
        # add cell [0] to list of dates
        dbTraining = [row]

# reading the test data from a csv file and populate dbTest
with open('optdigits.tes', newline='') as csvDataFile:
    # open file as csv file
    csvReader = csv.reader(csvDataFile)

    # loop over rows
    for row in csvReader:
        # add cell [0] to list of dates
        dbTest = [row]

# inititalizing the class votes for each test sample. Example: classVotes.append([0,0,0,0,0,0,0,0,0,0])
classVotes = [[0 for i in range(10)] for i in range(len(dbTest))]

print("Started my base and ensemble classifier ...")

accuracy = 0
for k in range(
        20):  # we will create 20 bootstrap samples here (k = 20). One classifier will be created for each bootstrap sample

    bootstrapSample = resample(dbTraining, n_samples=len(dbTraining), replace=True)

    # populate the values of X_training and y_training by using the bootstrapSample
    X_training = [row[:-1] for row in bootstrapSample]
    y_training = [row[-1] for row in bootstrapSample]
    # fitting the decision tree to the data
    clf = tree.DecisionTreeClassifier(criterion='entropy',
                                      max_depth=None)  # we will use a single decision tree without pruning it
    clf = clf.fit(X_training, y_training)

    for i, testSample in enumerate(dbTest):

        # make the classifier prediction for each test sample and update the corresponding index value in classVotes. For instance,
        # if your first base classifier predicted 2 for the first test sample, then classVotes[0,0,0,0,0,0,0,0,0,0] will change to classVotes[0,0,1,0,0,0,0,0,0,0].
        # Later, if your second base classifier predicted 3 for the first test sample, then classVotes[0,0,1,0,0,0,0,0,0,0] will change to classVotes[0,0,1,1,0,0,0,0,0,0]
        # Later, if your third base classifier predicted 3 for the first test sample, then classVotes[0,0,1,1,0,0,0,0,0,0] will change to classVotes[0,0,1,2,0,0,0,0,0,0]
        # this array will consolidate the votes of all classifier for all test samples
        predicted = clf.predict([testSample[:-1]])[0]
        classVotes[i][int(predicted)] += 1

        if k == 0 and predicted == testSample[
            -1]:  # for only the first base classifier, compare the prediction with the true label of the test sample here to start calculating its accuracy
            accuracy += 1

    if k == 0:  # for only the first base classifier, print its accuracy here
        accuracy /= len(dbTest)
        print("Finished my base classifier (fast but relatively low accuracy) ...")
        print("My base classifier accuracy: " + str(accuracy))
        print("")

    # now, compare the final ensemble prediction (majority vote in classVotes) for each test sample with the ground truth label to calculate the accuracy of the ensemble classifier (all base classifiers together)
    accuracy = 0

    for i, testSample in enumerate(dbTest):
        predicted = np.argmax(classVotes[i])
        if predicted == testSample[-1]:
            accuracy += 1

    accuracy /= len(dbTest)

# printing the ensemble accuracy here
print("Finished my ensemble classifier (slow but higher accuracy) ...")
print("My ensemble accuracy: " + str(accuracy))
print("")

print("Started Random Forest algorithm ...")

# Create a Random Forest Classifier
clf = RandomForestClassifier(
    n_estimators=20)  # this is the number of decision trees that will be generated by Random Forest. The sample of the ensemble method used before

# Fit Random Forest to the training data
X_training = [row[:-1] for row in dbTraining]
y_training = [row[-1] for row in dbTraining]
clf.fit(X_training, y_training)

# make the Random Forest prediction for each test sample. Example: class_predicted_rf = clf.predict([[3, 1, 2, 1, ...]]
for i, testSample in enumerate(dbTest):
    predicted = clf.predict([testSample[:-1]])[0]
    classVotes[i][int(predicted)] += 1

# compare the Random Forest prediction for each test sample with the ground truth label to calculate its accuracy
randomForestAccuracy = 0
for i in range(len(dbTest)):
    if np.argmax(classVotes[i]) == dbTest[i][-1]:
        randomForestAccuracy += 1

RFAccuracy = randomForestAccuracy / len(dbTest)

# printing Random Forest accuracy here
print("Random Forest accuracy: " + str(RFAccuracy))

print("Finished Random Forest algorithm (much faster and higher accuracy!) ...")
